# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: 'v$NEXT_MINOR_VERSION 🌈'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - feature
      - enhancement
  - title: '🐛 Bug Fixes'
    labels:
      - fix
      - bugfix
      - bug
  - title: '🧰 Maintenance'
    labels:
      - chore
      - dependencies
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
branches:
  - master
template: |
  ## What's Changed

  $CHANGES
